/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PokojeRouteImport } from './routes/pokoje'
import { Route as OkoliRouteImport } from './routes/okoli'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as CenikRouteImport } from './routes/cenik'
import { Route as IndexRouteImport } from './routes/index'

const PokojeRoute = PokojeRouteImport.update({
  id: '/pokoje',
  path: '/pokoje',
  getParentRoute: () => rootRouteImport,
} as any)
const OkoliRoute = OkoliRouteImport.update({
  id: '/okoli',
  path: '/okoli',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const CenikRoute = CenikRouteImport.update({
  id: '/cenik',
  path: '/cenik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/galerie': typeof GalerieRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/okoli': typeof OkoliRoute
  '/pokoje': typeof PokojeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/galerie': typeof GalerieRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/okoli': typeof OkoliRoute
  '/pokoje': typeof PokojeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cenik': typeof CenikRoute
  '/galerie': typeof GalerieRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/okoli': typeof OkoliRoute
  '/pokoje': typeof PokojeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cenik'
    | '/galerie'
    | '/kontakt'
    | '/o-nas'
    | '/okoli'
    | '/pokoje'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cenik' | '/galerie' | '/kontakt' | '/o-nas' | '/okoli' | '/pokoje'
  id:
    | '__root__'
    | '/'
    | '/cenik'
    | '/galerie'
    | '/kontakt'
    | '/o-nas'
    | '/okoli'
    | '/pokoje'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CenikRoute: typeof CenikRoute
  GalerieRoute: typeof GalerieRoute
  KontaktRoute: typeof KontaktRoute
  ONasRoute: typeof ONasRoute
  OkoliRoute: typeof OkoliRoute
  PokojeRoute: typeof PokojeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pokoje': {
      id: '/pokoje'
      path: '/pokoje'
      fullPath: '/pokoje'
      preLoaderRoute: typeof PokojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okoli': {
      id: '/okoli'
      path: '/okoli'
      fullPath: '/okoli'
      preLoaderRoute: typeof OkoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cenik': {
      id: '/cenik'
      path: '/cenik'
      fullPath: '/cenik'
      preLoaderRoute: typeof CenikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CenikRoute: CenikRoute,
  GalerieRoute: GalerieRoute,
  KontaktRoute: KontaktRoute,
  ONasRoute: ONasRoute,
  OkoliRoute: OkoliRoute,
  PokojeRoute: PokojeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
